### ISSUE TITLE
Notify Discord on Github Action pipeline failure

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-sources-mirror#27]
Allow the wider team to be aware of corrective action needed to get a pipeline running. Looks like this will be helpful in this effort: https://github.com/marketplace/actions/discord-workflow-status-notifier

**Comment by 2good4hisowngood** [comment]
To effectively implement the Discord Workflow Status Notifier in a GitHub Actions pipeline for failure alerts in Discord, it's recommended to set up organization-wide secrets. This approach ensures consistency across multiple pipelines and simplifies management.

Setting Up Organization Secrets:

    Access your GitHub organization's settings.
    Navigate to "Secrets" and select "New organization secret".
    Create the following secrets:
        discord-failure-webhook: Assign your Discord webhook URL as the value.
        avatar-url: Use a URL for your preferred avatar, like "https://raw.githubusercontent.com/Police-Data-Accessibility-Project/design-system/77f3106c0965d63db06800f15ab71ca33a880e4a/src/images/logo.svg".

This configuration allows for centralized updates, like changing the notification avatar across all repositories from a single location.

2. **Modify the Workflow YAML File**:
   - In your repository, create or modify a `.yml` workflow file under the `.github/workflows` directory.
   - Reference the following snippet to set up the Discord Notification job:

   ```yaml
   name: Build and Test
   on: [push, pull_request]  # Trigger on these events

   jobs:
     build:
       name: Build the Code
       # Add build steps here

     test:
       name: Test the Code
       # Add test steps here

     notify:
       name: Discord Notification
       runs-on: ubuntu-latest
       needs: [build, test]  # Ensure notification is sent after build and test jobs
       if: failure()  # Trigger only on failure

       steps:
         - name: Notify Discord
           uses: nobrayner/discord-webhook@v1
           with:
             github-token: ${{ secrets.GITHUB_TOKEN }}
             discord-webhook: ${{ secrets.discord-failure-webhook }}
             avatar-url: ${{ secrets.avatar-url }}
             title: '${{ github.repository }}: Failure'
             description: 'The repository ${{ github.repository }} has a failed pipeline. Check the details.'
   ```
   - This configuration triggers the notification only on pipeline failures and includes the repository name in the message.

3. **Commit and Test the Workflow**:
   - Commit and push these changes to your repository.
   - Test the workflow by triggering a build that fails to ensure the notification is sent to Discord.

These steps integrate the Discord Workflow Status Notifier into your GitHub Actions pipeline, configuring it to send failure alerts to a Discord channel with a custom avatar and including the repository name in the message.
